### ISSUE TITLE
When can you release a new version?

### ISSUE THREAD

**Issue by moesoha** [sgrif/mysqlclient-sys#14]
The current version on crates.io will cause a linking problem on Windows.

#10 fixes that but without a release. I have to add a patch in `Cargo.toml` like codes below to make it works.

```toml
[patch.crates-io]
mysqlclient-sys = { git = 'https://github.com/sgrif/mysqlclient-sys' }
```
